"use client";

import Link from "next/link";
import { useState } from "react";
import type { PlaylistDraft } from "@/lib/schemas/playlist";

const groups = {
  활동:["공부","운동","드라이브","휴식"], 분위기:["차분함","신나는","몽환적","감성적"],
  보컬:["보컬 적음","여성 보컬","남성 보컬"], 범위:["국내","해외","국내+해외"], 곡수:["5","10","15"],
};

export default function Home() {
  const [selected,setSelected]=useState<Record<string,string[]>>({활동:[],분위기:[],보컬:[],범위:["국내+해외"],곡수:["10"]});
  const [text,setText]=useState(""); const [status,setStatus]=useState(""); const [summary,setSummary]=useState("");
  const [playlist,setPlaylist]=useState<PlaylistDraft|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [saved,setSaved]=useState(false);
  const toggle=(group:string,value:string)=>setSelected((old)=>{ const multi=group==="분위기"; const has=old[group]?.includes(value); return {...old,[group]:multi?(has?old[group].filter(x=>x!==value):[...old[group],value]):has?[]:[value]}; });
  const request=()=>({conditions:[...(selected.활동??[]),...(selected.분위기??[]),...(selected.보컬??[])],region:selected.범위?.[0]==="국내"?"domestic":selected.범위?.[0]==="해외"?"global":"mixed",free_text:text||null,familiar_artists:[],count:Number(selected.곡수?.[0]??10)});
  async function recommend(){ setLoading(true);setError("");setSummary("");setPlaylist(null);setSaved(false); try { const response=await fetch("/api/agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request())}); if(!response.ok||!response.body) throw new Error(); const reader=response.body.getReader(); const decoder=new TextDecoder(); let buffer=""; while(true){const {done,value}=await reader.read(); if(done)break; buffer+=decoder.decode(value,{stream:true}); const rows=buffer.split("\n");buffer=rows.pop()??""; for(const row of rows){if(!row)continue;const event=JSON.parse(row);if(event.type==="status")setStatus(event.message);if(event.type==="tool")setStatus(({discover_music_candidates:"관련 아티스트를 찾고 있습니다.",verify_music_tracks:"실제 곡을 검증하고 있습니다.",compose_playlist:"플레이리스트를 구성하고 있습니다."} as Record<string,string>)[event.name]??"추천 중입니다.");if(event.type==="text_delta")setSummary((s)=>s+event.delta);if(event.type==="playlist")setPlaylist(event.data);if(event.type==="error")setError(event.message);}} }catch{setError("추천 서버에 연결할 수 없습니다. FastMCP 서버가 실행 중인지 확인해 주세요.");}finally{setLoading(false);} }
  async function save(){if(!playlist)return;try{const response=await fetch("/api/playlists",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({draft:playlist,idempotency_key:crypto.randomUUID()})});if(!response.ok)throw new Error();setSaved(true);}catch{setError("플레이리스트를 저장하지 못했습니다. 다시 시도해 주세요.");}}
  const disabled=!text.trim()&&!request().conditions.length;
  return <main className="shell"><header className="header"><div><div className="logo">MOODWAVE</div><div className="muted">상황과 분위기를 듣는 AI 큐레이터</div></div><Link className="secondary" href="/library">보관함</Link></header><section className="panel">{Object.entries(groups).map(([group,values])=><div className="group" key={group}><h2>{group}</h2><div className="choices">{values.map(value=><button className="chip" aria-pressed={selected[group]?.includes(value)??false} onClick={()=>toggle(group,value)} key={value}>{value}{group==="곡수"?"곡":""}</button>)}</div></div>)}<div className="group"><h2>추가 요청</h2><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="새벽에 코딩하면서 오래 들어도 피곤하지 않은 음악..." /></div><button className="primary" disabled={disabled||loading} onClick={recommend}>{loading?"큐레이팅 중...":"추천받기"}</button></section>{(loading||status)&&<div className="status" aria-live="polite">{loading&&"◌ "}{status}</div>}{error&&<div className="status error">{error}</div>}{summary&&<div className="summary"><strong>AI 큐레이터</strong><p>{summary}</p></div>}{playlist&&<><div className="actions"><h2 style={{marginRight:"auto"}}>{playlist.title}</h2><button className="primary" disabled={saved} onClick={save}>{saved?"저장 완료":"플레이리스트 저장"}</button></div><div className="grid">{playlist.tracks.map(track=><article className="card" key={track.recording_id}><img className="cover" src={track.cover_url??"/fallback-cover.svg"} onError={e=>{e.currentTarget.src="/fallback-cover.svg"}} alt={`${track.title} 앨범 표지`} /><h3>{track.title}</h3><div>{track.artist}</div><div className="muted">{track.release_title??"앨범 정보 미확인"}</div><span className="badge">{track.familiar?"익숙한 선택":"새로운 발견"}</span><a className="listen" target="_blank" rel="noreferrer" href={track.youtube_music_url}>YouTube Music에서 듣기</a></article>)}</div></>}</main>;
}
